export const strings = {
  name: "Kashan Ahmad",
  title: "Senior Frontend Software Engineer",
  summary:
    "Building beautifully animated yet performant web applications, I specialize in JavaScript, TypeScript, React, Next.js, and Tailwind CSS.",
  bio: [
    "Been shipping accessible web applications since 2018, I'm a creative software engineer with a passion for building beautifully animated yet performant web applications.",
    "Hailing from Pakistan, I self-taught myself how to code in JavaScript, TypeScript, and PHP. I ♥ open-source, and have shipped many open-source projects. I like pushing the boundaries of what's possible on the web, and I'm always eager to learn new things.",
    "Just recently, I built what most wouldn't even consider possible, a literal 3D Space Ship in the browser using React, GSAP, and Tailwind CSS. That's not it, the ship literally hyperdrives to a new page when you click on a link.",
  ],
  isOpenToWork: true,
  openToWork: "Open to work",
  openToWorkIcon: "bx:bx-bolt-circle",
  yearsOfExperience: "Years of experience",
  yearsOfExperienceCount: 5,
  yearsOfExperienceIcon: "bx:bx-award",
  experiences: "Experiences",
  experiencesIcon: "bx:bxs-cloud-download",
  projects: "Projects",
  projectsIcon: "bx:bxl-github",
  about: "About",
  blog: "Blog",
  resume: "Resume",
  contact: "Contact",
  contactLabel: "Get in touch",
  contactTagline:
    "My Mac stays on 24/7. I'll get back to you as soon as possible.",
  contactIcon: "bx:bx-mail-send",
  twitterHandle: "@oikashan",
  twitterIcon: "bx:bxl-twitter",
  githubUsername: "oikashan",
  githubIcon: "bx:bxl-github",
  linkedInUsername: "oikashani",
  linkedInIcon: "bx:bxl-linkedin",
  calendlyUsername: "oikashan",
  calendlyIcon: "bx:bx-calendar",
  website: "https://oikashan.com",
  websiteIcon: "bx:bx-world",
  emailAddress: "hi@oikashan.com",
  emailAddressIcon: "bx:bx-mail-send",
  address: "Rahim Yar Khan, Pakistan",
  addressIcon: "bx:bx-map",
  phoneNumber: "+92 302 5811158",
  phoneNumberIcon: "bx:bx-phone-call",
  ogImgAlt: "Kashan's Homepage",
};
