export const strings = {
  name: "Kashan Ahmad",
  title: "Senior Frontend Software Engineer",
  summary:
    "Building beautifully animated yet performant web applications, I specialize in JavaScript, TypeScript, React, Next.js, and Tailwind CSS.",
  bio: [
    "Been shipping accessible web applications since 2018, Kashan is an intuitive and creative software engineer with a passion for building beautifully animated yet performant web applications.",
    "Hailing from Pakistan, Kashan self-taught himself how to code in JavaScript, TypeScript, and PHP. He ♥ open-source, and has shipped many open-source projects. He is also a huge fan of React, Next.js, and Tailwind CSS.",
  ],
  openToWork: "Open to work",
  openToWorkIcon: "bx:bx-bolt-circle",
  yearsOfExperience: "Years of experience",
  yearsOfExperienceCount: 5,
  yearsOfExperienceIcon: "bx:bx-award",
  experiences: "Experiences",
  experiencesIcon: "bx:bxs-cloud-download",
  projects: "Projects",
  projectsIcon: "bx:bxl-github",
  about: "About",
  blog: "Blog",
  resume: "Resume",
  contact: "Contact",
  contactLabel: "Get in touch",
  contactIcon: "bx:bx-mail-send",
  twitterHandle: "@oikashan",
  twitterIcon: "bx:bxl-twitter",
  githubUsername: "oikashan",
  githubIcon: "bx:bxl-github",
  linkedInUsername: "oikashani",
  linkedInIcon: "bx:bxl-linkedin",
  website: "https://oikashan.com",
  websiteIcon: "bx:bx-world",
  ogImgAlt: "Kashan's Homepage",
};
